name: GitHub Actions Start
on: [push]
jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is automatically triggered job by a ${{ github.event_name }}"
      - run: echho "OS is ${{ runner.os }}"
