name: Greetings

on: [pull_request_target, issues]

jobs:
  send_greeting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for your first issue. Your issue will be reviewed by the team."
        pr-message: "Thanks for your first pull request. Well done!"
